{"name": "Title of your scenario outline -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n\tGetHandleVerifier [0x0x7ff61c9cfe75+79173]\n\tGetHandleVerifier [0x0x7ff61c9cfed0+79264]\n\t(No symbol) [0x0x7ff61c789e5a]\n\t(No symbol) [0x0x7ff61c7c7b85]\n\t(No symbol) [0x0x7ff61c7c2b1d]\n\t(No symbol) [0x0x7ff61c8167de]\n\t(No symbol) [0x0x7ff61c815f70]\n\t(No symbol) [0x0x7ff61c808743]\n\t(No symbol) [0x0x7ff61c7d14c1]\n\t(No symbol) [0x0x7ff61c7d2253]\n\tGetHandleVerifier [0x0x7ff61cc9a2ad+3004797]\n\tGetHandleVerifier [0x0x7ff61cc946fd+2981325]\n\tGetHandleVerifier [0x0x7ff61ccb3350+3107360]\n\tGetHandleVerifier [0x0x7ff61c9ea9fe+188622]\n\tGetHandleVerifier [0x0x7ff61c9f228f+219487]\n\tGetHandleVerifier [0x0x7ff61c9d8dc4+115860]\n\tGetHandleVerifier [0x0x7ff61c9d8f79+116297]\n\tGetHandleVerifier [0x0x7ff61c9bf528+11256]\n\tBaseThreadInitThunk [0x0x7ff92c8ee8d7+23]\n\tRtlUserThreadStart [0x0x7ff92d1bc34c+44]\n\n", "trace": "  File \"D:\\phython\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"steps\\login_step_defination.py\", line 15, in launch_chrome_browser\n    context.driver = webdriver.Chrome(options)\n                     ~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 67, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 260, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 357, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 448, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Chrome browser is launched", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n\tGetHandleVerifier [0x0x7ff61c9cfe75+79173]\n\tGetHandleVerifier [0x0x7ff61c9cfed0+79264]\n\t(No symbol) [0x0x7ff61c789e5a]\n\t(No symbol) [0x0x7ff61c7c7b85]\n\t(No symbol) [0x0x7ff61c7c2b1d]\n\t(No symbol) [0x0x7ff61c8167de]\n\t(No symbol) [0x0x7ff61c815f70]\n\t(No symbol) [0x0x7ff61c808743]\n\t(No symbol) [0x0x7ff61c7d14c1]\n\t(No symbol) [0x0x7ff61c7d2253]\n\tGetHandleVerifier [0x0x7ff61cc9a2ad+3004797]\n\tGetHandleVerifier [0x0x7ff61cc946fd+2981325]\n\tGetHandleVerifier [0x0x7ff61ccb3350+3107360]\n\tGetHandleVerifier [0x0x7ff61c9ea9fe+188622]\n\tGetHandleVerifier [0x0x7ff61c9f228f+219487]\n\tGetHandleVerifier [0x0x7ff61c9d8dc4+115860]\n\tGetHandleVerifier [0x0x7ff61c9d8f79+116297]\n\tGetHandleVerifier [0x0x7ff61c9bf528+11256]\n\tBaseThreadInitThunk [0x0x7ff92c8ee8d7+23]\n\tRtlUserThreadStart [0x0x7ff92d1bc34c+44]\n\n", "trace": "  File \"D:\\phython\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"steps\\login_step_defination.py\", line 15, in launch_chrome_browser\n    context.driver = webdriver.Chrome(options)\n                     ~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 67, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 260, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 357, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 448, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"D:\\phython\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750132948033, "stop": 1750132953489}, {"name": "When User navigates to OrangeHRM Login page", "status": "skipped", "start": 1750132953490, "stop": 1750132953490}, {"name": "Given I want to write a step with name1", "status": "broken", "statusDetails": {"message": "\nYou can implement step definitions for undefined steps with these snippets:\n\n@given(u'I want to write a step with name1')\ndef step_impl(context):\n    raise NotImplementedError(u'STEP: Given I want to write a step with name1')\n\n"}, "start": 1750132953490, "stop": 1750132953490}, {"name": "When I check for the 5 in step", "status": "broken", "statusDetails": {"message": "\nYou can implement step definitions for undefined steps with these snippets:\n\n@when(u'I check for the 5 in step')\ndef step_impl(context):\n    raise NotImplementedError(u'STEP: When I check for the 5 in step')\n\n"}, "start": 1750132953490, "stop": 1750132953490}, {"name": "Then I verify the success in step", "status": "broken", "statusDetails": {"message": "\nYou can implement step definitions for undefined steps with these snippets:\n\n@then(u'I verify the success in step')\ndef step_impl(context):\n    raise NotImplementedError(u'STEP: Then I verify the success in step')\n\n"}, "start": 1750132953490, "stop": 1750132953490}], "parameters": [{"name": "name", "value": "name1"}, {"name": "value", "value": "5"}, {"name": "status", "value": "success"}], "start": 1750132948032, "stop": 1750132953490, "uuid": "042d1574-5d73-4142-a382-3d6f8698c564", "historyId": "3bc1ad2b0ed77d220a66962f2153dd76", "fullName": "OrangeHRM Performance Module: Title of your scenario outline", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "tag"}, {"name": "tag", "value": "tag2"}, {"name": "feature", "value": "OrangeHRM Performance Module"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}